### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [B00merang-Project/Windows-Longhorn#11]
.

**Comment by cinnamoner** [comment]
![a939eb7a-2c16-11e6-9430-518b144c6cf6-2-1-1-1-1](https://cloud.githubusercontent.com/assets/15638605/17645780/f9285028-61b7-11e6-8e9f-79854ea75b5e.png)

**Comment by cinnamoner** [comment]
![ac134d42-2cec-11e6-96ba-4bb0abb7da88-1](https://cloud.githubusercontent.com/assets/15638605/17645814/e7f67b6c-61b8-11e6-9bbb-9bf5a07fe119.png)

**Comment by cinnamoner** [comment]
![a939eb7a-2c16-11e6-9430-518b144c6cf6-1-2](https://cloud.githubusercontent.com/assets/15638605/17645888/bf523fbe-61ba-11e6-8e4a-67ee08e7403e.png)

@feren Basically, I would like to replace the dark teal bar with this one and with these nav buttons and ...

**Comment by cinnamoner** [comment]
@feren Please tell, can I get the assets from high-res screenshots?

**Comment by cinnamoner** [comment]
@feren I would like those navs exactly as illustrated. In that pit and glowing up. Just some words of guidance, nothing more. Hmmm?

**Comment by cinnamoner** [comment]
@feren The window border will be grey, not baby-blue (like in Express).

**Comment by feren** [comment]
1. Yes, you can get hi-res assets from screenshots
2. Has @Elbullazul released Old Windows Basic? (He's the one making that theme)
3. Basic man, not Express, Windows Basic...

**Comment by dominichayesferen** [comment]
@cinnamoner 
The last time Elbullazul tried pits in GTK, it failed.

**Comment by cinnamoner** [comment]
> 1) Yes, you can get hi-res assets from screenshots
> 2) Has @Elbullazul released Old Windows Basic? (He's the one making that theme)
> 3) Basic man, not Express, Windows Basic...
> 4) The last time Elbullazul tried pits in GTK, it failed.

@feren 
1) Screenshots are typically 96 ppi. Not high enough for a quality print (at least 300 ppi), but monitors and printers work differently. 96 ppi looks swell on the monitor (pixel by pixel rendering). So, a 96 ppi screenshot is okay to pull assets from. At least that's how I see it. Hmmm?
2) Yeah, sure, he's making what you say he's making. I'm making a _"Media Player Edition"_. I've found no better name for it. What Elbullazul is making and what I am making are 2 different themes. Although  there might be some overlapping. Since I'm not intending to push anything (I don't even have privileges to do that in Longhorn repo and I'm not even asking for it yet), I don't think Elbullazul will be upset about my making this _Media Player Edition_ @Elbullazul, will you? For now is a local work, on my box.
3) Express or Basic, call it as you wish. I'm ignorant concerning those names and, truth to tell, they are of little relevance to me. But hey, thanks for trying.
4) Now, that one is important. Nav buttons in pits. For mor clarity, open up MP in Vista/7/Beta 2.

And let me emphasize it again: _The theme I'm making is inspired by Media Player 11.x_. Not just here and there, but coherently throughout the whole theme, okay? I've tried to be as precise and concise as I could. And thanks for the guidance, of course.

**Comment by cinnamoner** [comment]
@Elbullazul When you've got a little time, open up MP and tell me whether those nav button embedded in that pit are possible or not. Try to navigate forth and back (I want em glow as well).

**Comment by dominichayesferen** [comment]
@cinnamoner 
1. Just to let you know:
Express = The non-transparent version of Aero that eventually got given the name 'Standard' in Vista/7 Home Basic
Basic = No DWM at all on Windows Vista/7
2. _WMP Edition_?
3. Yep, I'd guess so about WMP Screenies (PS: If you have Vista, you can always scale up the DPI and/or Enable Large Text)

**Comment by cinnamoner** [comment]
@feren Thanks. The only unsettling issue is the nav buttons in the pit.

**Comment by cinnamoner** [comment]
@Elbullazul 
@feren 
@bluedxca93
I guess I'm on my own on this one. I only need help/guidance with the nav buttons in the pit. How is that accomplishable? If at all.

**Comment by dominichayesferen** [comment]
@cinnamoner I'd guess the only way (right now) to do it would to be either add pits to the toolbar BG itself, or make an icon set edit with half-pits on both back icons and forward icons...

**Comment by Elbullazul** [comment]
The icon option I'd say would be the easiest

**Comment by cinnamoner** [comment]
> The icon option I'd the easiest

@Elbullazul Thanks.

**Comment by cinnamoner** [comment]
By the way, she's not in mood for SEX.

**Comment by cinnamoner** [comment]
> an icon set edit with half-pits on both back icons and forward icons...

@feren Okay, I'll try to do it that way. Thanks.

**Comment by dominichayesferen** [comment]
Going offline temporarily, back in a few...

**Comment by dominichayesferen** [comment]
Ok, back now

**Comment by cinnamoner** [comment]
@feren Power outage? Get yourself a generator. UPS and a generator should do.

**Comment by dominichayesferen** [comment]
@cinnamoner 
No, deliberate power outage, we were getting electrics connected to a new portion of the house... (So yeah, no internet whilst that was going on)
